on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_SECRET }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: DRY-BUSH-9658 # e.g. 'my-project'
          directory: dist # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
